sudo: false
language: node_js
node_js:
- '4'
- '6'
- '7'
cache:
  directories:
  - node_modules
before_install:
- npm i -g npm@$(node -p "require('./package').engines.npm")
script:
- make lint
before_deploy:
- cd module
deploy:
  skip_cleanup: true
  provider: npm
  email: rr.rossmann@gmail.com
  api_key:
    secure: YJ5gIGRajMh/+KjeWAmWiZU8+YzE6NdiUY2M3jCXOAxYvWpMLsWHZRZGMowMWNvB2IEqhs01dlgitQvSirCgwYCq2QYVTtow5NREogTaB6gvL1R/mEts28HLogW6WrHwb47Xo2I2VwPrLhy0/ZKUg1TBXoNun+hnmuyYKJXt6veNeHE/IdQf0ydusT/sW3vkYVBy/v7+IYmDgCBLVPN5SdEqWBRQxF/tESHj1PrsnczsXXYv9PhkNyxaoUIuTMOx5W/X3g0IDOn+EAh8sjUWXSN9OyaVZhD1ffbT24DxNpcb+U0F5TTPSDbnGuLkKSkqL4MsfZGvQg3sUB1OdpRu/3R+S+2EqxXdT5lHlTBDwHnOzzYFW3s4oOyop00Gi4k1/eyOtxYG+oqk/3ClJT5KiFE2W+3SERRPH8hqbZU60tQ5BBM9O+jZ/KOrtNmYYr5IyRXR8nYGA2Z9RbqjHcz//MY/a24QXTiH6eouEgptQHUKx5KqvAJgX8umoVeiF5FLXvPuvNajnhcS8T6jQtceWSjYhCYsLj0K9UJHdIBgBf/raw9nn8ym9WUqDilpRlBIMpIwgq9nh1P/33MoZZjdLt+eoZjso53nj7hFjKhedCypDEs+ffAAxANcLaTCv0IWKb5vjo70fK+jAmQ9CVSPYBLMwdOX67cKvGjEX67i1QY=
  on:
    tags: true
    repo: Dreamscapes/promisified-core
    node: '7'
